# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Create a full review in rds

Globals:
    Function:
        Environment:
            Variables:
                REVIEW_PUBLISHED_SNS_TOPIC: !Ref ReviewPublishedSnsTopic
                RANKED_REVIEW_PUBLISHED_SNS_TOPIC: !Ref RankedReviewPublishedSnsTopic
                BATTLEGROUNDS_REVIEW_PUBLISHED_SNS_TOPIC: !Ref BattlegroundsReviewPublishedSnsTopic
                MERCENARIES_REVIEW_PUBLISHED_SNS_TOPIC: !Ref MercenariesReviewPublishedSnsTopic
                ARENA_REVIEW_PUBLISHED_SNS_TOPIC: !Ref ArenaReviewPublishedSnsTopic
                DUELS_HIGH_WINS_REVIEW_PUBLISHED_SNS_TOPIC: !Ref DuelsHighWinsReviewPublishedSnsTopic
                DUELS_REVIEW_PUBLISHED_SNS_TOPIC: !Ref DuelsReviewPublishedSnsTopic
                DUELS_RUN_END_PUBLISHED_SNS_TOPIC: !Ref DuelsRunEndPublishedSnsTopic
                BG_PERFECT_GAME_SNS_TOPIC: !Ref BgPerfectGameSnsTopic

Resources:
    ReviewPublishedSnsTopic:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: 'review-published'
            DisplayName: 'review-published'
    RankedReviewPublishedSnsTopic:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: 'ranked-review-published'
            DisplayName: 'ranked-review-published'
    BattlegroundsReviewPublishedSnsTopic:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: 'battlegrounds-review-published'
            DisplayName: 'battlegrounds-review-published'
    MercenariesReviewPublishedSnsTopic:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: 'mercenaries-review-published'
            DisplayName: 'mercenaries-review-published'
    ArenaReviewPublishedSnsTopic:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: 'arena-review-published'
            DisplayName: 'arena-review-published'
    DuelsHighWinsReviewPublishedSnsTopic:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: 'duels-high-wins-review-published'
            DisplayName: 'duels-high-wins-review-published'
    DuelsRunEndPublishedSnsTopic:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: 'duels-run-end-published'
            DisplayName: 'duels-run-end-published'
    DuelsReviewPublishedSnsTopic:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: 'duels-review-published'
            DisplayName: 'duels-review-published'
    BgPerfectGameSnsTopic:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: 'bg-perfect-game'
            DisplayName: 'bg-perfect-game'

    PopulateGameSummaryFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: create-full-review.default
            Runtime: nodejs18.x
            Timeout: 120
            CodeUri: ./dist/create-full-review
            MemorySize: 1200 # Increase memory to be able to handle big games like BGS
            ReservedConcurrentExecutions: 50
            Layers:
                - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Tags:
                LambdaName: trigger-create-full-review
            Policies:
                - AWSLambdaBasicExecutionRole
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSFullAccess
                - AmazonSQSFullAccess
                - AmazonS3FullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Events:
                SQSReplayOnS3Event:
                    Type: SQS
                    Properties:
                        Queue: arn:aws:sqs:us-west-2:478062583808:replay-uploaded
                        BatchSize: 1
