# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Create a full review in rds

# Globals:
#     Function:
#         Environment:
#             Variables:
#                 REVIEW_PUBLISHED_SNS_TOPIC: !Ref ReviewPublishedSnsTopic

Resources:
    # ReviewPublishedSnsTopic:
    #     Type: AWS::SNS::Topic
    #     Properties:
    #         TopicName: 'review-published'
    #         DisplayName: 'review-published'
    PopulateGameSummaryFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: create-full-review.default
            Runtime: nodejs10.x
            Timeout: 120
            CodeUri: ./dist/create-full-review
            MemorySize: 384 # Increase memory to be able to handle big games like BGS
            ReservedConcurrentExecutions: 40
            Tags:
                LambdaName: trigger-create-full-review
            Policies:
                - AWSLambdaBasicExecutionRole
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSFullAccess
                - AmazonSQSFullAccess
                - AmazonS3FullAccess
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Events:
                SQSReplayOnS3Event:
                    Type: SQS
                    Properties:
                        Queue: arn:aws:sqs:us-west-2:478062583808:replay-uploaded
                        BatchSize: 1
